added 7 api for enhancing (tor) The One Ring
Roll20/roll20-api-scripts pull request #1189
Opened 2021-01-18 04:34 UTC by Aragent

2021-01-19 14:25 UTC, Reonin requested changes
Hi @Aragent !
The versioning folders for tor-dice-checker etc should be the number referenced in the respective script.json. so the folder for those should be 
'tor-dice-checker/**0.1.1**/README.md'

It would be nice if each new script we're broken up into it's own pull request for clarity and if one breaks after the fixes we don't need to pull back all of the scripts and only the ones that are broken. 

Otherwise these apis look great

2021-02-23 15:50 UTC, dave-roll20 commented
Please limit pull requests to one API script.

2021-02-23 17:40 UTC, shdwjk commented
I talked to Nathanael Winget about this, it was a misunderstanding regarding policies of the repo.  He's getting it resolved.

2021-02-24 21:46 UTC, shdwjk commented on tor-dice-checker/script.json
> +    "0.1.1",
JSON does not permit hanging `,` (comma) in arrays and objects.

2021-02-24 21:47 UTC, shdwjk commented on tor-highlight-token-on-turn/script.json
> +    "0.1.1",
JSON does not permit hanging , (comma) in arrays and objects.

2021-02-24 21:50 UTC, shdwjk requested changes
They won't be able to merge your changes until you fix your `script.json` files.  They all contain:
```
"previousversions": [
  "0.1.1",
]
```
which is invalid JSON.  You need to use:
```
"previousversions": [
  "0.1.1"
]
```
(no hanging comma).  I highly recommend using a json linter like [jsonlint.com](http://jsonlint.com).

2021-02-24 21:50 UTC, shdwjk commented on tor-init-attributes/script.json
> +    "0.1.1",
JSON does not permit hanging , (comma) in arrays and objects.

2021-02-24 21:50 UTC, shdwjk commented on tor-mooks-state-checker/script.json
> +    "0.1.1",
JSON does not permit hanging , (comma) in arrays and objects.

2021-02-24 21:50 UTC, shdwjk commented on tor-stance-to-turn-order/script.json
> +    "0.1.1",
JSON does not permit hanging , (comma) in arrays and objects.

2021-02-24 21:50 UTC, shdwjk commented on tor-stances/script.json
> +    "0.1.1",
JSON does not permit hanging , (comma) in arrays and objects.

2021-02-24 21:50 UTC, shdwjk commented on tor-state-checker/script.json
> +    "0.1.1",
JSON does not permit hanging , (comma) in arrays and objects.

2021-08-30 21:42 UTC, NicholasR77 commented
@Aragent This pull request has been open for quite a while with no changes. As such, I'm going to go ahead and close it. Please feel to re-submit or re-open whenever you're ready for us to review the requested changes here.

2021-08-30 21:42 UTC, closed without merging