Add a WIP tool for building a directory listing of scripts
Roll20/roll20-api-scripts pull request #1197
Opened 2021-01-20 22:04 UTC by jcbwlkr

I was talking to @kentonh about making a directory listing of what scripts already exist. This is just an idea and needs a lot of styling.

![Screen Shot 2021-01-20 at 4 03 22 PM](https://user-images.githubusercontent.com/2027263/105246592-1942be00-5b39-11eb-9815-f7ba61d19631.png)

![Screen Shot 2021-01-20 at 4 03 30 PM](https://user-images.githubusercontent.com/2027263/105246644-295a9d80-5b39-11eb-8140-e08057ca71e9.png)

To finish this it needs better CSS and maybe more content to show in the final pages. Some of the data uses inconsistent typing which needs to be addressed before those fields can be used.

2021-02-20 13:49 UTC, shdwjk commented
This is a neat project, but it's not an API script. It belongs in another repo.

2021-02-20 15:50 UTC, Anduh requested changes
As Aaron said, this PR doesn't belong here, but you could post about this on the forums.

2021-02-20 15:59 UTC, jcbwlkr commented
Oh hi! I forgot about this lol

So to clarify I did this as a personal favor / proof of concept for @kentonh at Roll20 because he was looking for something like this. I have no intention of maintaining this and don't care if it is merged or even used.

Feel free to close this PR if you want.

2021-04-19 21:41 UTC, closed without merging

2021-04-19 21:42 UTC, NicholasR77 commented
Closing with approval as seen here: https://github.com/Roll20/roll20-api-scripts/pull/1197#issuecomment-782704464