[SimpleSound 2.1] Initial upload
Roll20/roll20-api-scripts pull request #1448
Opened 2022-02-05 21:25 UTC by lazy468

2022-02-06 15:48 UTC, Anduh commented on SimpleSound/script.json
> +    "description": "The goal of this script is to play/stop sound effects from the Roll20 Jukebox via macro and chat commands.",
```suggestion
    "description": "The goal of this script is to play/stop sound effects from the Roll20 Jukebox via macro and chat commands.\n\nCommands: `!splay trackname`, `!sstop trackname`, `!sstop`(stops all), `!swhisper`(toggle the GM whisper status)\n\nSee [Readme](https://github.com/Roll20/roll20-api-scripts/blob/master/SimpleSound/Readme.md) for full instructions",
```
Link to Readme + show some commands makes it easier to get started.

2022-02-06 15:49 UTC, Anduh requested changes
The extra GPL license should probably be removed. By submitting the API to the repo, you're agreeing to the repo's [existing MIT license](https://github.com/Roll20/roll20-api-scripts#license).

Tnaks for submitting it to the API menu, will make it easier to use!

2022-02-07 02:20 UTC, lazy468 commented
Very good, I've removed the extra licensing information and committed your suggestion to description. Thanks!

2022-02-07 10:29 UTC, Anduh requested changes
Glad to help!

Few more things I noticed:
* Each API version needs to be in a folder, including the latest one. API authors just commonly leave a version of the latest version in the root folder so it's easier to find for those navigating the repo, but it's in no way necessary. 
* As this is the initial publishing of the API, IMO you can just simplify and only upload version `2.1`, given the trivial changes between `2.0` and `2.1`
* `2.0/Simplesounds.js` still have the GPL license in the comments

2022-02-07 10:32 UTC, Anduh commented on SimpleSound/script.json
> +    "description": "The goal of this script is to play/stop sound effects from the Roll20 Jukebox via macro and chat commands.\n\nCommands: `!splay trackname`, `!sstop trackname`, `!sstop`(stops all)
```suggestion
    "description": "The goal of this script is to play/stop sound effects from the Roll20 Jukebox via macro and chat commands.\n\nCommands: `!splay trackname`, `!sstop trackname`, `!sstop`(stops all), `!swhisper`(toggle the GM whisper status)\n\nSee [Readme](https://github.com/Roll20/roll20-api-scripts/blob/master/SimpleSound/Readme.md) for full instructions\n\n[API:Simple Sound](https://app.roll20.net/forum/post/10593263/script-simple-sound)-forum thread",
```

2022-02-07 10:32 UTC, Anduh commented on SimpleSound/script.json
> +    "description": "The goal of this script is to play/stop sound effects from the Roll20 Jukebox via macro and chat commands.\n\nCommands: `!splay trackname`, `!sstop trackname`, `!sstop`(stops all)
```suggestion
    "description": "The goal of this script is to play/stop sound effects from the Roll20 Jukebox via macro and chat commands.\n\nCommands: `!splay trackname`, `!sstop trackname`, `!sstop`(stops all), `!swhisper`(toggle the GM whisper status)\n\nSee [Readme](https://github.com/Roll20/roll20-api-scripts/blob/master/SimpleSound/Readme.md) for full instructions\n\n[API:Simple Sound](https://app.roll20.net/forum/post/10593263/script-simple-sound)-forum thread",
```

2022-02-07 10:38 UTC, Anduh commented on SimpleSound/script.json
> +    "description": "The goal of this script is to play/stop sound effects from the Roll20 Jukebox via macro and chat commands.\n\nCommands: `!splay trackname`, `!sstop trackname`, `!sstop`(stops all)
```suggestion
    "description": "The goal of this script is to play/stop sound effects from the Roll20 Jukebox via macro and chat commands.\n\nCommands: `!splay trackname`, `!sstop trackname`, `!sstop`(stops all), `!swhisper`(toggle the GM whisper status)\n\nSee [Readme](https://github.com/Roll20/roll20-api-scripts/blob/master/SimpleSound/Readme.md) for full instructions\n\n[API:Simple Sound](https://app.roll20.net/forum/post/10593263/script-simple-sound)-forum thread",
```

2022-02-07 10:38 UTC, Anduh commented on SimpleSound/script.json
> +    "description": "The goal of this script is to play/stop sound effects from the Roll20 Jukebox via macro and chat commands.\n\nCommands: `!splay trackname`, `!sstop trackname`, `!sstop`(stops all)
```suggestion
    "description": "The goal of this script is to play/stop sound effects from the Roll20 Jukebox via macro and chat commands.\n\nCommands: `!splay trackname`, `!sstop trackname`, `!sstop`(stops all), `!swhisper`(toggle the GM whisper status)\n\nSee [Readme](https://github.com/Roll20/roll20-api-scripts/blob/master/SimpleSound/Readme.md) for full instructions\n\n[API:Simple Sound](https://app.roll20.net/forum/post/10593263/script-simple-sound)-forum thread",
```

2022-02-07 22:56 UTC, NicholasR77 approved these changes

2022-02-07 22:56 UTC, merged